<a href="https://colab.research.google.com/github/SOUJU07/DSMP-Notebooks/blob/main/Copy_of_session_19_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [96]:
# code here
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

In [99]:
titanic_df.groupby('Pclass')['Age'].agg(
    avg_age='mean',
    missing=lambda x:x.isna().sum()
)

          avg_age  missing
Pclass
1       38.233441       30
2       29.877630       11
3       25.140620      136

In [88]:
titanic_df[titanic_df['Age'].isna()].groupby('Pclass')

Pclass
1     30
2     11
3    136
Name: PassengerId, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [108]:
# code here
titanic_df['Embarked'] = titanic_df.groupby('Pclass')['Embarked'].transform(lambda x: x.fillna(x.mode()[0]))

titanic_df.groupby('Pclass')['Embarked'].value_counts(ascending=True)

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [111]:
# code here

grp = titanic_df.groupby(['Embarked', 'Pclass'])['Fare'].mean()
grp = grp.round(2)
result = {}

for (embarked, pclass), fare in grp.items():
    if embarked not in result:
        result[embarked] = {}
    result[embarked][pclass] = fare
grp

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.51
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [116]:
# code here

import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [121]:

fifa_df['Team']

0          Qatar
1        Ecuador
2        England
3           Iran
4        Senegal
         ...
123      Morocco
124      Croatia
125      Morocco
126    Argentina
127       France
Name: Team, Length: 128, dtype: object

In [117]:
# code here
def z_normalization(group, cols_to_perform):
    for col in cols_to_perform:
        std = group[col].std()
        mean = group[col].mean()
        group[f"{col}_z_norm"] = (group[col] - mean)/std
    return group


cols_to_perform = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]
groups = fifa_df.groupby("Team")
groups = groups.apply(z_normalization, cols_to_perform = cols_to_perform).groupby("Team")
groups.agg(
{
    "Passes": ["min", "max"],
    "Yellow Cards": ["min", "max", "mean"],
    "Attempted Line Breaks": ["max", "min", "std"],
    "Possession (%)": "mean"
})

/tmp/ipython-input-2243772054.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  groups = groups.apply(z_normalization, cols_to_perform = cols_to_perform).groupby("Team")

ValueError: 'Team' is both an index level and a column label, which is ambiguous.

In [125]:
def z_normalization(group, cols_to_perform):
    for col in cols_to_perform:
        mean = group[col].mean()
        std = group[col].std()
        group[col] = (group[col] - mean) / std
    return group
cols_to_normalize = [
    'Passes',
    'Passes Completed',
    'Attempted Line Breaks',
    'Completed Line Breaks'
]
normalized_df = df.groupby('Team').apply(
    z_normalization,
    cols_to_perform=cols_to_normalize
)

normalized_df = normalized_df.reset_index(drop=True)

final_result = normalized_df.groupby('Team').agg(
    min_passes=('Passes', 'min'),
    max_passes=('Passes', 'max'),
    min_yellow_cards=('Yellow Cards', 'min'),
    max_yellow_cards=('Yellow Cards', 'max'),
    avg_yellow_cards=('Yellow Cards', 'mean'),
    max_attempted_lb=('Attempted Line Breaks', 'max'),
    min_attempted_lb=('Attempted Line Breaks', 'min'),
    std_attempted_lb=('Attempted Line Breaks', 'std'),
    avg_possession=('Possession', 'mean')
)

KeyError: 'Team'

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [5]:
# code here
ipl=pd.read_csv('/content/ipl_deliveries.csv')
chasing=ipl[ipl['innings']==2]
chasing.groupby(['ID','batter'])['batsman_run'].sum().sort_values(ascending=False)

ID       batter
501206   PC Valthaty      120
501243   V Sehwag         119
1254061  SV Samson        119
1136620  SR Watson        117
336018   ST Jayasuriya    114
                         ...
501221   DE Bollinger       0
501220   LRPL Taylor        0
501221   R Ashwin           0
1304112  VR Iyer            0
         UT Yadav           0
Name: batsman_run, Length: 6972, dtype: int64

In [6]:
chasing

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
120,1312200,Rajasthan RoyalsGujarat Titans,2,0,1,WP Saha,TA Boult,Shubman Gill,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
121,1312200,Rajasthan RoyalsGujarat Titans,2,0,2,WP Saha,TA Boult,Shubman Gill,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
122,1312200,Rajasthan RoyalsGujarat Titans,2,0,3,WP Saha,TA Boult,Shubman Gill,NaN,1,0,1,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
123,1312200,Rajasthan RoyalsGujarat Titans,2,0,4,Shubman Gill,TA Boult,WP Saha,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
124,1312200,Rajasthan RoyalsGujarat Titans,2,0,5,Shubman Gill,TA Boult,WP Saha,NaN,0,0,0,0,0,NaN,NaN,NaN,Gujarat Titans,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [7]:
df=chasing.groupby('batter').agg({
    'ballnumber':'count',
    'batsman_run':'sum'
})

df=df[df['ballnumber']>100]
df['strike rate']=(df['batsman_run']/df['ballnumber'])*100
df.sort_values('strike rate',ascending=False)

                ballnumber  batsman_run  strike rate
batter
PJ Cummins             119          222   186.554622
LS Livingstone         111          182   163.963964
AD Russell             605          986   162.975207
SP Narine              376          599   159.308511
V Sehwag               906         1427   157.505519
...                    ...          ...          ...
LR Shukla              149          137    91.946309
R Dhawan               102           92    90.196078
GH Vihari              200          179    89.500000
B Kumar                168          150    89.285714
K Goel                 122           97    79.508197

[184 rows x 3 columns]

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [31]:
# code here
ipl.head(2)
new_df=ipl[ipl['isWicketDelivery']==1]
dismis=new_df.groupby(['batter','bowler'])['isWicketDelivery'].count().sort_values(ascending=False)

dismis

batter          bowler
RG Sharma       SP Narine        8
                A Mishra         7
MS Dhoni        Z Khan           7
PA Patel        B Kumar          7
MS Dhoni        PP Ojha          7
                                ..
A Ashish Reddy  KA Pollard       1
                DJ Bravo         1
                BW Hilfenhaus    1
                AD Russell       1
                A Nehra          1
Name: isWicketDelivery, Length: 8745, dtype: int64

In [32]:
runs=ipl.groupby(['batter','bowler'])['batsman_run'].sum().sort_values(ascending=False)
runs.head(20)

batter          bowler
DA Warner       SP Narine          176
SK Raina        PP Chawla          175
V Kohli         R Ashwin           160
                A Mishra           158
                DJ Bravo           157
                UT Yadav           150
KL Rahul        JJ Bumrah          147
S Dhawan        Harbhajan Singh    147
RG Sharma       PP Chawla          146
DA Warner       YS Chahal          145
V Kohli         JJ Bumrah          145
RG Sharma       UT Yadav           144
V Kohli         RA Jadeja          140
RG Sharma       SP Narine          137
KA Pollard      DJ Bravo           136
                A Mishra           136
S Dhawan        DJ Bravo           132
SK Raina        Harbhajan Singh    132
AB de Villiers  JJ Bumrah          131
CH Gayle        B Kumar            131
Name: batsman_run, dtype: int64

In [37]:
runs=ipl.groupby(['batter','bowler'])['batsman_run'].sum()
df = pd.concat([dismis, runs], axis=1)
df.sort_values(['isWicketDelivery','batsman_run'],ascending=[False,True]).head(10)

                           isWicketDelivery  batsman_run
batter     bowler
RG Sharma  SP Narine                    8.0          137
PA Patel   B Kumar                      7.0           65
MS Dhoni   Z Khan                       7.0           74
V Kohli    Sandeep Sharma               7.0           78
RG Sharma  A Mishra                     7.0           87
MS Dhoni   PP Ojha                      7.0           98
RV Uthappa R Ashwin                     7.0          123
RG Sharma  R Vinay Kumar                6.0           22
Q de Kock  YS Chahal                    6.0           44
RG Sharma  SK Trivedi                   6.0           45

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [48]:
# code here
ipl.head()
ipl['pair']=ipl.apply(lambda x:tuple(sorted([x['batter'],x['non-striker']])),axis=1)
ipl.groupby('pair')['total_run'].sum().sort_values(ascending=False).head(10)

pair
(AB de Villiers, V Kohli)    3134
(CH Gayle, V Kohli)          2802
(DA Warner, S Dhawan)        2357
(G Gambhir, RV Uthappa)      1906
(KL Rahul, MA Agarwal)       1731
(CH Gayle, KL Rahul)         1633
(MS Dhoni, SK Raina)         1482
(PP Shaw, S Dhawan)          1461
(DA Warner, JM Bairstow)     1401
(RR Pant, SS Iyer)           1368
Name: total_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [81]:
# code here
pair=ipl.groupby('pair')

pair_stats = ipl.groupby('pair').agg(
    Runs=('total_run', 'sum'),
    Balls=('ballnumber', 'count'),
    Outs=('isWicketDelivery', 'sum')
).reset_index()

pair_stats['Avg'] = pair_stats['Runs'] / pair_stats['Outs']
pair_stats['StrikeRate'] = (pair_stats['Runs'] / pair_stats['Balls']) * 100
pair_stats[['batsman1','batsman2']]=pd.DataFrame(pair_stats['pair'].tolist())

pair_stats[['batsman1','batsman2','Runs','Balls','Outs','Avg','StrikeRate']].sort_values(by='Runs',ascending=False).head(10)

            batsman1     batsman2  Runs  Balls  Outs        Avg  StrikeRate
302   AB de Villiers      V Kohli  3134   2059    71  44.140845  152.209811
1251        CH Gayle      V Kohli  2802   1973    53  52.867925  142.017233
1508       DA Warner     S Dhawan  2357   1725    49  48.102041  136.637681
1954       G Gambhir   RV Uthappa  1906   1425    48  39.708333  133.754386
2803        KL Rahul   MA Agarwal  1731   1211    33  52.454545  142.939719
1228        CH Gayle     KL Rahul  1633   1208    36  45.361111  135.182119
3420        MS Dhoni     SK Raina  1482   1074    49  30.244898  137.988827
3708         PP Shaw     S Dhawan  1461   1035    44  33.204545  141.159420
1485       DA Warner  JM Bairstow  1401    971    26  53.884615  144.284243
3947         RR Pant      SS Iyer  1368   1059    37  36.972973  129.178470