In [8]:
!pip install sqlalchemy pymysql pandas

Requirement already satisfied: sqlalchemy in c:\users\tuku mapa\anaconda3\lib\site-packages (1.4.32)
Requirement already satisfied: pymysql in c:\users\tuku mapa\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: pandas in c:\users\tuku mapa\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\tuku mapa\anaconda3\lib\site-packages (from sqlalchemy) (1.1.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\tuku mapa\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\tuku mapa\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\tuku mapa\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\tuku mapa\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [11]:
from sqlalchemy import create_engine
import pandas as pd

In [14]:
engine = create_engine("mysql+pymysql://root:1234@127.0.0.1/temp_db")

print("Connected Successfully 🚀")

Connected Successfully 🚀

In [15]:
df1 = pd.read_sql("SELECT * FROM invoices", engine)

df1.head()

,Order Id,Date,Meal Id,Company Id,Date of Meal,Participants,Meal Price,Type of Meal
0,839FKFW2LLX4LMBB,27-05-2016,INBUX904GIHI8YBD,LJKS5NK6788CYMUU,2016-05-31 07:00:00+02:00,['David Bishop'],469,Breakfast
1,97OX39BGVMHODLJM,27-09-2018,J0MMOOPP709DIDIE,LJKS5NK6788CYMUU,2018-10-01 20:00:00+02:00,['David Bishop'],22,Dinner
2,041ORQM5OIHTIU6L,24-08-2014,E4UJLQNCI16UX5CS,LJKS5NK6788CYMUU,2014-08-23 14:00:00+02:00,['Karen Stansell'],314,Lunch
3,YT796QI18WNGZ7ZJ,2014-12-04 00:00:00,C9SDFHF7553BE247,LJKS5NK6788CYMUU,2014-04-07 21:00:00+02:00,['Addie Patino'],438,Dinner
4,6YLROQT27B6HRF4E,28-07-2015,48EQXS6IHYNZDDZ5,LJKS5NK6788CYMUU,2015-07-27 14:00:00+02:00,['Addie Patino' 'Susan Guerrero'],690,Lunch

In [16]:
df2 = pd.read_sql('SELECT * FROM orderleads',engine)

df2.head()

,Order Id,Company Id,Company Name,Date,Order Value,Converted
0,80EYLOKP9E762WKG,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,18-02-2017,4875,1
1,TLEXR1HZWTUTBHPB,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,30-07-2015,8425,0
2,839FKFW2LLX4LMBB,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,27-05-2016,4837,0
3,97OX39BGVMHODLJM,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,27-09-2018,343,0
4,5T4LGH4XGBWOD49Z,LJKS5NK6788CYMUU,Chimera-Chasing Casbah,14-01-2016,983,0

In [17]:
df3 = pd.read_sql('SELECT * FROM salesteam',engine)

df3.head()

,Sales Rep,Sales Rep Id,Company Name,Company Id
0,Jessie Mcallister,97UNNAT790E0WM4N,Chimera-Chasing Casbah,LJKS5NK6788CYMUU
1,Jessie Mcallister,97UNNAT790E0WM4N,Tangential Sheds,36MFTZOYMTAJP1RK
2,Jessie Mcallister,97UNNAT790E0WM4N,Two-Mile Grab,H3JRC7XX7WJAD4ZO
3,Jessie Mcallister,97UNNAT790E0WM4N,Three-Men-And-A-Helper Congo'S,HB25MDZR0MGCQUGX
4,Jessie Mcallister,97UNNAT790E0WM4N,Biophysical Battleground,7RVA8TIVBLBXMNO4

In [18]:
with pd.ExcelWriter('output.xlsx') as writer:  
    df1.to_excel(writer, sheet_name='Sheet_name_1')
    df2.to_excel(writer, sheet_name='Sheet_name_2')
    df3.to_excel(writer, sheet_name='Sheet_name_3')

In [88]:
import requests

url = "https://wft-geo-db.p.rapidapi.com/v1/geo/cities"

querystring = {"countryIds":"IN"}

headers = {
"x-rapidapi-key": "1fc64e4c19mshc1a96a2ad5264cap18d0b4jsn597849cac5bd",
"x-rapidapi-host": "wft-geo-db.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()['data']

links = response.json()['links']

metadata = response.json()['metadata']

In [90]:
data

[{'id': 3236469,
  'wikiDataId': 'Q490676',
  'type': 'CITY',
  'city': 'Aadityana',
  'name': 'Aadityana',
  'country': 'India',
  'countryCode': 'IN',
  'region': 'Gujarat',
  'regionCode': 'GJ',
  'regionWdId': 'Q1061',
  'latitude': 21.741388888,
  'longitude': 69.698338888,
  'population': 0},
 {'id': 57674,
  'wikiDataId': 'Q519770',
  'type': 'CITY',
  'city': 'Aalo',
  'name': 'Aalo',
  'country': 'India',
  'countryCode': 'IN',
  'region': 'Arunachal Pradesh',
  'regionCode': 'AR',
  'regionWdId': 'Q1162',
  'latitude': 28.17,
  'longitude': 94.77,
  'population': 18425},
 {'id': 3216432,
  'wikiDataId': 'Q4663214',
  'type': 'CITY',
  'city': 'Abadgarh',
  'name': 'Abadgarh',
  'country': 'India',
  'countryCode': 'IN',
  'region': 'Punjab',
  'regionCode': 'PB',
  'regionWdId': 'Q22424',
  'latitude': 32.1,
  'longitude': 75.6,
  'population': 0},
 {'id': 2985050,
  'wikiDataId': 'Q4666150',
  'type': 'ADM2',
  'city': 'Abdullapurmet mandal',
  'name': 'Abdullapurmet mandal',
  'country': 'India',
  'countryCode': 'IN',
  'region': 'Telangana',
  'regionCode': 'TS',
  'regionWdId': 'Q677037',
  'latitude': 17.30971111,
  'longitude': 78.68305278,
  'population': 156067},
 {'id': 57610,
  'wikiDataId': 'Q4667324',
  'type': 'CITY',
  'city': 'Abhaneri',
  'name': 'Abhaneri',
  'country': 'India',
  'countryCode': 'IN',
  'region': 'Rajasthan',
  'regionCode': 'RJ',
  'regionWdId': 'Q1437',
  'latitude': 26.9499868,
  'longitude': 76.6196097,
  'population': 1424}]

In [91]:
count = metadata['totalCount']//5

In [92]:
next_url = links[1]['href']

In [93]:
import time

for i in range(1,count):
    
    url = "https://wft-geo-db.p.rapidapi.com"
    page = url + next_url

    response = requests.get(page, headers=headers)
    print(response)
    
    links = response.json()['links']
    print(links)
    
    for item in links:
        if item['rel']=='next':
            next_url=item['href']
    
    data.extend(response.json()['data'])
    
    time.sleep(1)

<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=10&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=5&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=15&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=10&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=20&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=15&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=25&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=20&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=30&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=25&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=35&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=30&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=40&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=35&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=45&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=40&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=50&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=45&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=55&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=50&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=60&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=55&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=65&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=60&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=70&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=65&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=75&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=70&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=80&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=75&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=85&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=80&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=90&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=85&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=95&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=90&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=100&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=95&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=105&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=100&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=110&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=105&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=115&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=110&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=120&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=115&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=125&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=120&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=130&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=125&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=135&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=130&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=140&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=135&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=145&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=140&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=150&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=145&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=155&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=150&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=160&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=155&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=165&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=160&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=170&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=165&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=175&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=170&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=180&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=175&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=185&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=180&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=190&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=185&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=195&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=190&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=200&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=195&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=205&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=200&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=210&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=205&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=215&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=210&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=220&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=215&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=225&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=220&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=230&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=225&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=235&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=230&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=240&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=235&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=245&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=240&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=250&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=245&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=255&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=250&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=260&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=255&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=265&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=260&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=270&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=265&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=275&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=270&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=280&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=275&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=285&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=280&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=290&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=285&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=295&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=290&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=300&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=295&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=305&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=300&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=310&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>
[{'rel': 'first', 'href': '/v1/geo/cities?offset=0&limit=5&countryIds=IN'}, {'rel': 'prev', 'href': '/v1/geo/cities?offset=305&limit=5&countryIds=IN'}, {'rel': 'next', 'href': '/v1/geo/cities?offset=315&limit=5&countryIds=IN'}, {'rel': 'last', 'href': '/v1/geo/cities?offset=7005&limit=5&countryIds=IN'}]
<Response [200]>

KeyboardInterrupt:

In [94]:
limit = 10
offset = 0
all_data = []

while offset<101:
    url = f"https://wft-geo-db.p.rapidapi.com/v1/geo/cities?countryIds=IN&limit={limit}&offset={offset}"

    response = requests.get(url, headers=headers)
    data_json = response.json()

    cities = data_json.get("data", [])
    print(cities)

    if not cities:
        break

    all_data.extend(cities)
    offset += limit
    print('all_data :',all_data)

    print(f"Fetched {offset} rows")
    time.sleep(1)

[{'id': 3236469, 'wikiDataId': 'Q490676', 'type': 'CITY', 'city': 'Aadityana', 'name': 'Aadityana', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 21.741388888, 'longitude': 69.698338888, 'population': 0}, {'id': 57674, 'wikiDataId': 'Q519770', 'type': 'CITY', 'city': 'Aalo', 'name': 'Aalo', 'country': 'India', 'countryCode': 'IN', 'region': 'Arunachal Pradesh', 'regionCode': 'AR', 'regionWdId': 'Q1162', 'latitude': 28.17, 'longitude': 94.77, 'population': 18425}, {'id': 3216432, 'wikiDataId': 'Q4663214', 'type': 'CITY', 'city': 'Abadgarh', 'name': 'Abadgarh', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 32.1, 'longitude': 75.6, 'population': 0}, {'id': 2985050, 'wikiDataId': 'Q4666150', 'type': 'ADM2', 'city': 'Abdullapurmet mandal', 'name': 'Abdullapurmet mandal', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 17.30971111, 'longitude': 78.68305278, 'population': 156067}, {'id': 57610, 'wikiDataId': 'Q4667324', 'type': 'CITY', 'city': 'Abhaneri', 'name': 'Abhaneri', 'country': 'India', 'countryCode': 'IN', 'region': 'Rajasthan', 'regionCode': 'RJ', 'regionWdId': 'Q1437', 'latitude': 26.9499868, 'longitude': 76.6196097, 'population': 1424}, {'id': 3427445, 'wikiDataId': 'Q4667322', 'type': 'CITY', 'city': 'Abhanpur', 'name': 'Abhanpur', 'country': 'India', 'countryCode': 'IN', 'region': 'Chhattisgarh', 'regionCode': 'CG', 'regionWdId': 'Q1168', 'latitude': 21.05277778, 'longitude': 81.74555556, 'population': 14432}, {'id': 56795, 'wikiDataId': 'Q490701', 'type': 'CITY', 'city': 'Abhayapuri', 'name': 'Abhayapuri', 'country': 'India', 'countryCode': 'IN', 'region': 'Assam', 'regionCode': 'AS', 'regionWdId': 'Q1164', 'latitude': 26.33, 'longitude': 90.67, 'population': 15847}, {'id': 3408665, 'wikiDataId': 'Q4667364', 'type': 'CITY', 'city': 'Abhepur', 'name': 'Abhepur', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.66666667, 'longitude': 76.83333333, 'population': 0}, {'id': 56805, 'wikiDataId': 'Q490715', 'type': 'CITY', 'city': 'Abiramam', 'name': 'Abiramam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 9.47, 'longitude': 78.45, 'population': 8144}, {'id': 57561, 'wikiDataId': 'Q490878', 'type': 'CITY', 'city': 'Abohar', 'name': 'Abohar', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.1334, 'longitude': 74.2001, 'population': 145302}]
all_data : [{'id': 3236469, 'wikiDataId': 'Q490676', 'type': 'CITY', 'city': 'Aadityana', 'name': 'Aadityana', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 21.741388888, 'longitude': 69.698338888, 'population': 0}, {'id': 57674, 'wikiDataId': 'Q519770', 'type': 'CITY', 'city': 'Aalo', 'name': 'Aalo', 'country': 'India', 'countryCode': 'IN', 'region': 'Arunachal Pradesh', 'regionCode': 'AR', 'regionWdId': 'Q1162', 'latitude': 28.17, 'longitude': 94.77, 'population': 18425}, {'id': 3216432, 'wikiDataId': 'Q4663214', 'type': 'CITY', 'city': 'Abadgarh', 'name': 'Abadgarh', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 32.1, 'longitude': 75.6, 'population': 0}, {'id': 2985050, 'wikiDataId': 'Q4666150', 'type': 'ADM2', 'city': 'Abdullapurmet mandal', 'name': 'Abdullapurmet mandal', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 17.30971111, 'longitude': 78.68305278, 'population': 156067}, {'id': 57610, 'wikiDataId': 'Q4667324', 'type': 'CITY', 'city': 'Abhaneri', 'name': 'Abhaneri', 'country': 'India', 'countryCode': 'IN', 'region': 'Rajasthan', 'regionCode': 'RJ', 'regionWdId': 'Q1437', 'latitude': 26.9499868, 'longitude': 76.6196097, 'population': 1424}, {'id': 3427445, 'wikiDataId': 'Q4667322', 'type': 'CITY', 'city': 'Abhanpur', 'name': 'Abhanpur', 'country': 'India', 'countryCode': 'IN', 'region': 'Chhattisgarh', 'regionCode': 'CG', 'regionWdId': 'Q1168', 'latitude': 21.05277778, 'longitude': 81.74555556, 'population': 14432}, {'id': 56795, 'wikiDataId': 'Q490701', 'type': 'CITY', 'city': 'Abhayapuri', 'name': 'Abhayapuri', 'country': 'India', 'countryCode': 'IN', 'region': 'Assam', 'regionCode': 'AS', 'regionWdId': 'Q1164', 'latitude': 26.33, 'longitude': 90.67, 'population': 15847}, {'id': 3408665, 'wikiDataId': 'Q4667364', 'type': 'CITY', 'city': 'Abhepur', 'name': 'Abhepur', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.66666667, 'longitude': 76.83333333, 'population': 0}, {'id': 56805, 'wikiDataId': 'Q490715', 'type': 'CITY', 'city': 'Abiramam', 'name': 'Abiramam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 9.47, 'longitude': 78.45, 'population': 8144}, {'id': 57561, 'wikiDataId': 'Q490878', 'type': 'CITY', 'city': 'Abohar', 'name': 'Abohar', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.1334, 'longitude': 74.2001, 'population': 145302}]
Fetched 10 rows
[{'id': 57712, 'wikiDataId': 'Q490916', 'type': 'CITY', 'city': 'Abrama', 'name': 'Abrama', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 20.583411111, 'longitude': 72.942311111, 'population': 21000}, {'id': 57589, 'wikiDataId': 'Q490659', 'type': 'CITY', 'city': 'Abu Road', 'name': 'Abu Road', 'country': 'India', 'countryCode': 'IN', 'region': 'Rajasthan', 'regionCode': 'RJ', 'regionWdId': 'Q1437', 'latitude': 24.48, 'longitude': 72.78, 'population': 55599}, {'id': 57248, 'wikiDataId': 'Q490886', 'type': 'CITY', 'city': 'Achalpur', 'name': 'Achalpur', 'country': 'India', 'countryCode': 'IN', 'region': 'Maharashtra', 'regionCode': 'MH', 'regionWdId': 'Q1191', 'latitude': 21.257222222, 'longitude': 77.508611111, 'population': 112311}, {'id': 2998850, 'wikiDataId': 'Q4673455', 'type': 'CITY', 'city': 'Achampet', 'name': 'Achampet', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 16.629858333, 'longitude': 80.121316666, 'population': 57313}, {'id': 57325, 'wikiDataId': 'Q490739', 'type': 'CITY', 'city': 'Achhnera', 'name': 'Achhnera', 'country': 'India', 'countryCode': 'IN', 'region': 'Uttar Pradesh', 'regionCode': 'UP', 'regionWdId': 'Q1498', 'latitude': 27.18, 'longitude': 77.77, 'population': 20532}, {'id': 57036, 'wikiDataId': 'Q2350169', 'type': 'CITY', 'city': 'Adalaj', 'name': 'Adalaj', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 23.1646919, 'longitude': 72.5821046, 'population': 11957}, {'id': 3924363, 'wikiDataId': 'Q137259706', 'type': 'CITY', 'city': 'Adalgaon', 'name': 'Adalgaon', 'country': 'India', 'countryCode': 'IN', 'region': 'Maharashtra', 'regionCode': 'MH', 'regionWdId': 'Q1191', 'latitude': 18.63631, 'longitude': 74.76381, 'population': 0}, {'id': 3316147, 'wikiDataId': 'Q4661775', 'type': 'CITY', 'city': 'Adambakkam', 'name': 'Adambakkam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 12.99, 'longitude': 80.2, 'population': 0}, {'id': 3516555, 'wikiDataId': 'Q490783', 'type': 'CITY', 'city': 'Adampur', 'name': 'Adampur', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 31.43, 'longitude': 75.72, 'population': 20922}, {'id': 3177752, 'wikiDataId': 'Q4680786', 'type': 'CITY', 'city': 'Adapur', 'name': 'Adapur', 'country': 'India', 'countryCode': 'IN', 'region': 'Karnataka', 'regionCode': 'KA', 'regionWdId': 'Q1185', 'latitude': 26.95, 'longitude': 84.96666667, 'population': 1022}]
all_data : [{'id': 3236469, 'wikiDataId': 'Q490676', 'type': 'CITY', 'city': 'Aadityana', 'name': 'Aadityana', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 21.741388888, 'longitude': 69.698338888, 'population': 0}, {'id': 57674, 'wikiDataId': 'Q519770', 'type': 'CITY', 'city': 'Aalo', 'name': 'Aalo', 'country': 'India', 'countryCode': 'IN', 'region': 'Arunachal Pradesh', 'regionCode': 'AR', 'regionWdId': 'Q1162', 'latitude': 28.17, 'longitude': 94.77, 'population': 18425}, {'id': 3216432, 'wikiDataId': 'Q4663214', 'type': 'CITY', 'city': 'Abadgarh', 'name': 'Abadgarh', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 32.1, 'longitude': 75.6, 'population': 0}, {'id': 2985050, 'wikiDataId': 'Q4666150', 'type': 'ADM2', 'city': 'Abdullapurmet mandal', 'name': 'Abdullapurmet mandal', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 17.30971111, 'longitude': 78.68305278, 'population': 156067}, {'id': 57610, 'wikiDataId': 'Q4667324', 'type': 'CITY', 'city': 'Abhaneri', 'name': 'Abhaneri', 'country': 'India', 'countryCode': 'IN', 'region': 'Rajasthan', 'regionCode': 'RJ', 'regionWdId': 'Q1437', 'latitude': 26.9499868, 'longitude': 76.6196097, 'population': 1424}, {'id': 3427445, 'wikiDataId': 'Q4667322', 'type': 'CITY', 'city': 'Abhanpur', 'name': 'Abhanpur', 'country': 'India', 'countryCode': 'IN', 'region': 'Chhattisgarh', 'regionCode': 'CG', 'regionWdId': 'Q1168', 'latitude': 21.05277778, 'longitude': 81.74555556, 'population': 14432}, {'id': 56795, 'wikiDataId': 'Q490701', 'type': 'CITY', 'city': 'Abhayapuri', 'name': 'Abhayapuri', 'country': 'India', 'countryCode': 'IN', 'region': 'Assam', 'regionCode': 'AS', 'regionWdId': 'Q1164', 'latitude': 26.33, 'longitude': 90.67, 'population': 15847}, {'id': 3408665, 'wikiDataId': 'Q4667364', 'type': 'CITY', 'city': 'Abhepur', 'name': 'Abhepur', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.66666667, 'longitude': 76.83333333, 'population': 0}, {'id': 56805, 'wikiDataId': 'Q490715', 'type': 'CITY', 'city': 'Abiramam', 'name': 'Abiramam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 9.47, 'longitude': 78.45, 'population': 8144}, {'id': 57561, 'wikiDataId': 'Q490878', 'type': 'CITY', 'city': 'Abohar', 'name': 'Abohar', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 30.1334, 'longitude': 74.2001, 'population': 145302}, {'id': 57712, 'wikiDataId': 'Q490916', 'type': 'CITY', 'city': 'Abrama', 'name': 'Abrama', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 20.583411111, 'longitude': 72.942311111, 'population': 21000}, {'id': 57589, 'wikiDataId': 'Q490659', 'type': 'CITY', 'city': 'Abu Road', 'name': 'Abu Road', 'country': 'India', 'countryCode': 'IN', 'region': 'Rajasthan', 'regionCode': 'RJ', 'regionWdId': 'Q1437', 'latitude': 24.48, 'longitude': 72.78, 'population': 55599}, {'id': 57248, 'wikiDataId': 'Q490886', 'type': 'CITY', 'city': 'Achalpur', 'name': 'Achalpur', 'country': 'India', 'countryCode': 'IN', 'region': 'Maharashtra', 'regionCode': 'MH', 'regionWdId': 'Q1191', 'latitude': 21.257222222, 'longitude': 77.508611111, 'population': 112311}, {'id': 2998850, 'wikiDataId': 'Q4673455', 'type': 'CITY', 'city': 'Achampet', 'name': 'Achampet', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 16.629858333, 'longitude': 80.121316666, 'population': 57313}, {'id': 57325, 'wikiDataId': 'Q490739', 'type': 'CITY', 'city': 'Achhnera', 'name': 'Achhnera', 'country': 'India', 'countryCode': 'IN', 'region': 'Uttar Pradesh', 'regionCode': 'UP', 'regionWdId': 'Q1498', 'latitude': 27.18, 'longitude': 77.77, 'population': 20532}, {'id': 57036, 'wikiDataId': 'Q2350169', 'type': 'CITY', 'city': 'Adalaj', 'name': 'Adalaj', 'country': 'India', 'countryCode': 'IN', 'region': 'Gujarat', 'regionCode': 'GJ', 'regionWdId': 'Q1061', 'latitude': 23.1646919, 'longitude': 72.5821046, 'population': 11957}, {'id': 3924363, 'wikiDataId': 'Q137259706', 'type': 'CITY', 'city': 'Adalgaon', 'name': 'Adalgaon', 'country': 'India', 'countryCode': 'IN', 'region': 'Maharashtra', 'regionCode': 'MH', 'regionWdId': 'Q1191', 'latitude': 18.63631, 'longitude': 74.76381, 'population': 0}, {'id': 3316147, 'wikiDataId': 'Q4661775', 'type': 'CITY', 'city': 'Adambakkam', 'name': 'Adambakkam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 12.99, 'longitude': 80.2, 'population': 0}, {'id': 3516555, 'wikiDataId': 'Q490783', 'type': 'CITY', 'city': 'Adampur', 'name': 'Adampur', 'country': 'India', 'countryCode': 'IN', 'region': 'Punjab', 'regionCode': 'PB', 'regionWdId': 'Q22424', 'latitude': 31.43, 'longitude': 75.72, 'population': 20922}, {'id': 3177752, 'wikiDataId': 'Q4680786', 'type': 'CITY', 'city': 'Adapur', 'name': 'Adapur', 'country': 'India', 'countryCode': 'IN', 'region': 'Karnataka', 'regionCode': 'KA', 'regionWdId': 'Q1185', 'latitude': 26.95, 'longitude': 84.96666667, 'population': 1022}]
Fetched 20 rows
[{'id': 3364244, 'wikiDataId': 'Q4680825', 'type': 'CITY', 'city': 'Adargunchi', 'name': 'Adargunchi', 'country': 'India', 'countryCode': 'IN', 'region': 'Karnataka', 'regionCode': 'KA', 'regionWdId': 'Q1185', 'latitude': 15.2816139, 'longitude': 75.1530788, 'population': 0}, {'id': 3409393, 'wikiDataId': 'Q4680894', 'type': 'CITY', 'city': 'Adawad', 'name': 'Adawad', 'country': 'India', 'countryCode': 'IN', 'region': 'Maharashtra', 'regionCode': 'MH', 'regionWdId': 'Q1191', 'latitude': 21.216666666, 'longitude': 75.45, 'population': 0}, {'id': 3901781, 'wikiDataId': 'Q65665421', 'type': 'CITY', 'city': 'Addanki', 'name': 'Addanki', 'country': 'India', 'countryCode': 'IN', 'region': 'Andhra Pradesh', 'regionCode': 'AP', 'regionWdId': 'Q1159', 'latitude': 15.811, 'longitude': 79.9738, 'population': 43850}, {'id': 3412610, 'wikiDataId': 'Q11904154', 'type': 'CITY', 'city': 'Adegaon', 'name': 'Adegaon', 'country': 'India', 'countryCode': 'IN', 'region': 'Madhya Pradesh', 'regionCode': 'MP', 'regionWdId': 'Q1188', 'latitude': 22.61666667, 'longitude': 79.48333333, 'population': 0}, {'id': 3435098, 'wikiDataId': 'Q4682676', 'type': 'CITY', 'city': 'Adibatla', 'name': 'Adibatla', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 17.23333333, 'longitude': 78.55, 'population': 0}, {'id': 3024304, 'wikiDataId': 'Q12990125', 'type': 'CITY', 'city': 'Adigoppula', 'name': 'Adigoppula', 'country': 'India', 'countryCode': 'IN', 'region': 'Andhra Pradesh', 'regionCode': 'AP', 'regionWdId': 'Q1159', 'latitude': 16.4401661, 'longitude': 79.6235407, 'population': 8816}, {'id': 147728, 'wikiDataId': 'Q494281', 'type': 'CITY', 'city': 'Adilabad', 'name': 'Adilabad', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 19.669, 'longitude': 78.53548, 'population': 117167}, {'id': 3212273, 'wikiDataId': 'Q15211', 'type': 'ADM2', 'city': 'Adilabad district', 'name': 'Adilabad district', 'country': 'India', 'countryCode': 'IN', 'region': 'Telangana', 'regionCode': 'TS', 'regionWdId': 'Q677037', 'latitude': 19.669, 'longitude': 78.53548, 'population': 2741239}, {'id': 57045, 'wikiDataId': 'Q490694', 'type': 'CITY', 'city': 'Adirampattinam', 'name': 'Adirampattinam', 'country': 'India', 'countryCode': 'IN', 'region': 'Tamil Nadu', 'regionCode': 'TN', 'regionWdId': 'Q1445', 'latitude': 10.2, 'longitude': 79.24, 'population': 31066}, {'id': 3331060, 'wikiDataId': 'Q4683239', 'type': 'CITY', 'city': 'Adki', 'name': 'Adki', 'country': 'India', 'countryCode': 'IN', 'region': 'Karnataka', 'regionCode': 'KA', 'regionWdId': 'Q1185', 'latitude': 17.11666667, 'longitude': 77.36666667, 'population': 0}]

In [96]:
df=pd.DataFrame(all_data)

In [97]:
df

,id,wikiDataId,type,city,name,country,countryCode,region,regionCode,regionWdId,latitude,longitude,population
0,3236469,Q490676,CITY,Aadityana,Aadityana,India,IN,Gujarat,GJ,Q1061,21.741389,69.698339,0
1,57674,Q519770,CITY,Aalo,Aalo,India,IN,Arunachal Pradesh,AR,Q1162,28.170000,94.770000,18425
2,3216432,Q4663214,CITY,Abadgarh,Abadgarh,India,IN,Punjab,PB,Q22424,32.100000,75.600000,0
3,2985050,Q4666150,ADM2,Abdullapurmet mandal,Abdullapurmet mandal,India,IN,Telangana,TS,Q677037,17.309711,78.683053,156067
4,57610,Q4667324,CITY,Abhaneri,Abhaneri,India,IN,Rajasthan,RJ,Q1437,26.949987,76.619610,1424
...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,3804371,Q120467632,CITY,Alampur Deha,Alampur Deha,India,IN,Uttar Pradesh,UP,Q1498,27.093460,78.799230,0
106,3804835,Q123694694,CITY,Alampur Kotla,Alampur Kotla,India,IN,Uttar Pradesh,UP,Q1498,27.289110,78.352920,0
107,3078112,Q4706017,CITY,Alamuru,Alamuru,India,IN,Andhra Pradesh,AP,Q1159,16.783330,81.900000,9723
108,57753,Q2738477,CITY,Aland,Aland,India,IN,Karnataka,KA,Q1185,17.570000,76.570000,42371
109,3506041,Q12915163,ADM2,Aland Taluk,Aland Taluk,India,IN,Karnataka,KA,Q1185,17.541000,76.591000,0

In [98]:
import pymysql
from sqlalchemy import create_engine

In [100]:
engine = create_engine("mysql+pymysql://root:1234@localhost/temp_db")
# {root}:{password}@{url}/{database}
df.to_sql('cities', con = engine, if_exists = 'append')

110

'<!DOCTYPE html><html lang=en><meta charset=UTF-8><meta content="width=device-width,initial-scale=1"name=viewport><title>Flipkart reCAPTCHA</title><link href=https://static-assets-web.flixcart.com/batman-returns/batman-returns/s/recaptcha.css rel=stylesheet><script src="https://www.google.com/recaptcha/enterprise.js?render=6Lc49B0pAAAAAIVgOhfwW8i7t7SRO0KSnlSVZRAq"></script><script src=https://static-assets-web.flixcart.com/apex-static/js/recaptcha-enterprise-v1.js async defer></script><div class=container><img alt="Flipkart Logo"class=logo src="https://rukminim1.flixcart.com/www/60/60/promos/14/06/2024/88011666-ce1d-40f0-a8eb-1bac7d164885.png?q=60"><h1 class=header>Are you a human?</h1><p class=subText>Confirming...<div class=loaderContainer><div class=loader></div></div></div>'

[]